### ISSUE TITLE
Uploading style images

### ISSUE THREAD

**Issue by MduRouge** [AbdullahAlfaraj/neural-style-website#1]
Hi Abdullah,

Thanks for sharing your work. It seems pretty neat. I'm going to to set it up today to try it. 

I was reading your post and saw that you chose to create an upload voor content, but not for style images. Is it possible to add the upload style images as well? Would be a nice addition. Let me know what you think, thanks!

**Comment by AbdullahAlfaraj** [comment]
Hi MduRouge, 
after you setup the website, you should copy/move all of your images, styles and content, to one folder.
This folder is the "neural-style-website/public/uploads" directory. 

On the main page you will see "Select Content" click on it if you want to select an image as the content image. Click on "Select Style" to select one or more style images.
Select Content:
<img src="https://raw.githubusercontent.com/AbdullahAlfaraj/neural-style-website/master/screenshot/select-content.png" width="380px" />
Select Style:
<img src="https://raw.githubusercontent.com/AbdullahAlfaraj/neural-style-website/master/screenshot/select-two-styles.png" width="380px" />

here is the full list of the screenshots:
https://github.com/AbdullahAlfaraj/neural-style-website/tree/master/screenshot 

as you can see from the screenshots both "select content" and "select styles" have access to the same set of images.

I'm currently working on the feature that allow you to upload images from the Internet or your machine to the server uploads directory by typing the path of the image. If this what you are asking then yes I think it's an essential feature to include.  
Tell me if you're faced with any problem/difficulties during the setup.

**Comment by MduRouge** [comment]
Hi Abdullah,

Thanks for your explanation. I was talking about the option to upload images from the internet or machine. Great to hear you are developing this as wel, I'll stay tuned!

**Comment by AbdullahAlfaraj** [comment]
Hi MduRouge, 
I just finished adding the upload feature.You could now upload images to the server in two ways:
- upload by using image url.
- upload one or multiple images directly from your device .

**Comment by MduRouge** [comment]
Hi Abdullah,

Great. I'm currently trying to set it up. I got stuck installing Typescript using:

npm install -g typescript

I get the following result:

ocia@ocia-Server:~$ npm install -g typescript
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/typescript
npm WARN checkPermissions Missing write access to /usr/lib/node_modules
/usr/lib
└── typescript@1.8.10 

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "-g" "typescript"
npm ERR! node v0.10.44
npm ERR! npm  v3.8.8
npm ERR! path /usr/lib/node_modules/typescript
npm ERR! code EACCES

npm ERR! Error: EACCES, access '/usr/lib/node_modules/typescript'
npm ERR!     at module.exports (/usr/lib/node_modules/npm/lib/install/access-error.js:4:18)
npm ERR!     at /usr/lib/node_modules/npm/lib/install/writable.js:30:25
npm ERR!     at /usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:232:16
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR!  { [Error: EACCES, access '/usr/lib/node_modules/typescript'] code: 'EACCES', path: '/usr/lib/node_modules/typescript' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ocia/npm-debug.log

Is there a way to fix this or to get TypeScript installed? Thanks!

**Comment by AbdullahAlfaraj** [comment]
it seems you need to install TypeScript as the root/Administrator. if you are on Linux try 

``` sh
sudo npm install -g typescript
```

**Comment by MduRouge** [comment]
Got a bit stuck yesterday. I'm running the following setup:

Ubuntu 14.04

Installed:

Node.js v6.0.0 current
npm 3.8.8
Mongodb-org (ubuntu)
Gulp

When I ran step #3 of the setup, I get a lot of Errors (check below). I ignored those and installed and run Gulp and finally run:

bash neural-style-website-up.sh

After running the command above, there is a short pop up from a terminal window, which closes immediately. When I try to to enter the website via the internal or external address, it states that it is unable to connect. Is there something I'm missing?  Maybe Mongodb needs a special setup? Would like to try your site, really appreciate the help, thanks.

ERRORS When running #3 from setup:

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "run" "tsc"
npm ERR! node v5.11.0
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! neural-style-website@0.1.0 tsc: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the neural-style-website@0.1.0 tsc script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the neural-style-website package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs neural-style-website
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls neural-style-website
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ocia/neural-style-website/npm-debug.log

**Comment by AbdullahAlfaraj** [comment]
when you run the bash script "neural-style-website-up.sh" it will open two terminal tabs. The first tab for mongodb and the second tab for NodeJs server. when an error occurs the tabs will close immediately.
as you stated, the error most likely related to Mongodb. Please type these two commands manually in a terminal :

``` sh
mongod
```

you should see something like "waiting for connections on port 27017".
If you see an error it could be that you haven't setup mongodb correctly. For example you need to create the "/data/db" directory in the root directory of you computer and give mongodb read/write access privilege.

In a new tab run the second command to

``` sh
node socket
```

you should see "the server is up on http://localhost:4000"
if you get any error please post them here and I will try my best to help you.

**Comment by MduRouge** [comment]
Back again:)! Current status when i type the following command:

mongod

2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] MongoDB starting : pid=28425 port=27017 dbpath=/data/db 64-bit host=ocia-Server
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] db version v3.2.6
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] git version: 05552b562c7a0b3143a729aaa0838e558dc49b25
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] allocator: tcmalloc
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] modules: none
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] build environment:
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten]     distmod: ubuntu1404
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten]     distarch: x86_64
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten]     target_arch: x86_64
2016-05-03T12:45:15.850+0200 I CONTROL  [initandlisten] options: {}
2016-05-03T12:45:15.886+0200 E NETWORK  [initandlisten] listen(): bind() failed errno:98 Address already in use for socket: 0.0.0.0:27017
2016-05-03T12:45:15.886+0200 E NETWORK  [initandlisten]   addr already in use
2016-05-03T12:45:15.886+0200 E STORAGE  [initandlisten] Failed to set up sockets during startup.
2016-05-03T12:45:15.886+0200 I CONTROL  [initandlisten] dbexit:  rc: 48

And when I run 

node socket

module.js:341
    throw err;
    ^

Error: Cannot find module '/home/ocia/socket'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.

When I run 

bash neural-style-website-up.sh

It opens a new terminal which states: 

the server is up on http://localhost:4000

So it seems that I'm one step closer, but not quite there yet. Also you mentioned to add the /data/db to my root directory, however Iḿ not allowed to use the / in a filename, correct? Thanks for the help!

**Comment by MduRouge** [comment]
Update: I can access the website through de localhost:4000, but not externally from the serverip..

**Comment by AbdullahAlfaraj** [comment]
Hi MduRouge,
There are multiple things I would like to address. 
1) to access the website from a different device on the same network. You need to find the local IP address of your main device (server). For example, I have my server assigned the local ip address "192.168.1.9". If I would like to access the website from my secondary machine, I would have to log in to the same network, and access the website using the following URL  "http://192.168.1.9:4000/"

2) can you tell me if the website load correctly when you access it using "http://localhost:4000/".
try to compare what you get with what you see in the ScreenShots from [README.md](https://github.com/AbdullahAlfaraj/neural-style-website/blob/master/README.md)
if the website is similar to the screenshots then proceed by clicking the "Run" button and observe the log section. If you keep seeing the text "The log message is empty" in the log section after click "Run", it is probably because you haven't configured mongodb correctly or you might have forgotten to setup the "neural-style" project that is located in "neural-style-website/neural-style"

Here is a post that go in depth of how to give permission to mongodb to read/write from/to your server 
http://stackoverflow.com/a/7948986

**Comment by cnekTep** [comment]
Hi, when i run `node socet`, I see this error:

cnektep@ubuntus:~/neural-style-website$ node socket

/home/cnektep/neural-style-website/socket.js:36
    fs.readdir(`${rootDir}/${dir}`, function(err, files) {
               ^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by cnekTep** [comment]
hmmm, I update node js to 4.4.3, and now have new error:

cnektep@ubuntus:~/neural-style-website$ node socket
module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^
Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/cnektep/neural-style-website/node_modules/stream-mmmagic/node_modules/mmmagic/index.js:3:13)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by AbdullahAlfaraj** [comment]
Hi guys, I will close this issue. I would like to organize the conversation, so that it's easier to find relevant information.  
cnekTep, I opened an issue (#2) that address your problem. 
MduRouge, if you still have difficulties with mongodb, I would like to continue the conversation in an another issue.
